from typing import Dict


ITEM_TO_HEX: Dict[str, int] = {
    "Green Rupee": 0x01,
    "Blue Rupee": 0x02,
    "Yellow Rupee": 0x03,
    "Red Rupee": 0x04,
    "Purple Rupee": 0x05,
    "Orange Rupee": 0x06,
    "Silver Rupee": 0x07,
    "Links Purple Rupee": 0xED,
    "Bombs (5)": 0x0A,
    "Bombs (10)": 0x0B,
    "Bombs (20)": 0x0C,
    "Bombs (30)": 0x0D,
    "Arrows (10)": 0x0E,
    "Arrows (20)": 0x0F,
    "Arrows (30)": 0x10,
    "Seeds (50)": 0x12,
    "Water Bombs (3)": 0x19,
    "Water Bombs (5)": 0x16,
    "Water Bombs (10)": 0x17,
    "Water Bombs (15)": 0x18,
    "Bomblings (3)": 0x1C,
    "Bomblings (5)": 0x1A,
    "Bomblings (10)": 0x1B,
    "Piece of Heart": 0x21,
    "Heart Container": 0x22,
    "Progressive Master Sword": 0x29,
    "Ordon Shield": 0x2A,
    "Hylian Shield": 0x2C,
    "Magic Armor": 0x30,
    "Zora Armor": 0x31,
    "Shadow Crystal": 0x32,
    "Progressive Wallet": 0x36,
    "Hawkeye": 0x3E,
    "Gale Boomerang": 0x40,
    "Spinner": 0x41,
    "Ball and Chain": 0x42,
    "Progressive Hero's Bow": 0x43,
    "Progressive Clawshot": 0x46,
    "Iron Boots": 0x45,
    "Progressive Dominion Rod": 0x46,
    "Lantern": 0x48,
    "Progressive Fishing Rod": 0x4A,
    "Slingshot": 0x4B,
    "Giant Bomb Bag": 0x4F,
    "Empty Bomb Bag": 0x50,
    "Goron Bomb Bag": 0x51,
    "Empty Bottle (Fishing Hole)": 0x60,
    "Milk (half) (Sera Bottle)": 0x65,
    "Lantern Oil (Coro Bottle)": 0x9D,
    "Great Fairy Tears (Jovani)": 0x75,
    "Horse Call": 0x84,
    "Forest Temple Small Key": 0x85,
    "Goron Mines Small Key": 0x86,
    "Lakebed Temple Small Key": 0x87,
    "Arbiter's Grounds Small Key": 0x88,
    "Snowpeak Ruins Small Key": 0x89,
    "Temple of Time Small Key": 0x8A,
    "City in the Sky Small Key": 0x8B,
    "Palace of Twilight Small Key": 0x8C,
    "Hyrule Castle Small Key": 0x8D,
    "Gerudo Desert Bublin Camp Key": 0x8E,
    "Small Key (North Faron Gate)": 0xEE,
    "Small Key (Coro)": 0xFE,
    "North Faron Woods Gate Keys": 0xF3,
    "Aurus's Memo": 0x90,
    "Ashei's Sketch": 0x91,
    "Forest Temple Big Key": 0x92,
    "Lakebed Temple Big Key": 0x93,
    "Goron Mines Key Shard": 0xF8,
    "Arbiter's Grounds Big Key": 0x94,
    "Bedroom Key": 0xF6,
    "Temple of Time Big Key": 0x95,
    "City in the Sky Big Key": 0x96,
    "Palace of Twilight Big Key": 0x97,
    "Hyrule Castle Big Key": 0x98,
    "Forest Temple Compass": 0x99,
    "Goron Mines Compass": 0x9A,
    "Lakebed Temple Compass": 0x9B,
    "Arbiter's Grounds Compass": 0xA8,
    "Snowpeak Ruins Compass": 0xA9,
    "Temple of Time Compass": 0xAA,
    "City in the Sky Compass": 0xAB,
    "Palace of Twilight Compass": 0xAC,
    "Hyrule Castle Compass": 0xAD,
    "Forest Temple Map": 0xB6,
    "Goron Mines Map": 0xB7,
    "Lakebed Temple Map": 0xB8,
    "Arbiter's Grounds Map": 0xB9,
    "Snowpeak Ruins Map": 0xBA,
    "Temple of Time Map": 0xBB,
    "City in the Sky Map": 0xBC,
    "Palace of Twilight Map": 0xBD,
    "Hyrule Castle Map": 0xBE,
    "Male Beetle": 0xC0,
    "Female Beetle": 0xC1,
    "Male Butterfly": 0xC2,
    "Female Butterfly": 0xC3,
    "Male Stag Beetle": 0xC4,
    "Female Stag Beetle": 0xC5,
    "Male Grasshopper": 0xC6,
    "Female Grasshopper": 0xC7,
    "Male Phasmid": 0xC8,
    "Female Phasmid": 0xC9,
    "Male Pill Bug": 0xCA,
    "Female Pill Bug": 0xCB,
    "Male Mantis": 0xCC,
    "Female Mantis": 0xCD,
    "Male Ladybug": 0xCE,
    "Female Ladybug": 0xCF,
    "Male Snail": 0xD0,
    "Female Snail": 0xD1,
    "Male Dragonfly": 0xD2,
    "Female Dragonfly": 0xD3,
    "Male Ant": 0xD4,
    "Female Ant": 0xD5,
    "Male Dayfly": 0xD6,
    "Female Dayfly": 0xD7,
    "Progressive Mirror Shard": 0xA5,
    "Progressive Fused Shadow": 0xD8,
    "Progressive Hidden Skill": 0xE1,
    "Progressive Sky Book": 0xE9,
    "Poe Soul": 0xE0,
    "Poe 1 (Fire)": 0xEF,
    "Poe 2 (Fire)": 0xF0,
    "Poe 3 (Fire)": 0xF1,
    "Poe 4 (Fire)": 0xF2,
    "Ordon Pumpkin": 0xF4,
    "Ordon Goat Cheese": 0xF5,
    "Ice Trap": 0x13,
}
